name: 'OPS status checker'

on: 
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  status_checker_job:
    name: Look for build warnings
    runs-on: ubuntu-latest
    permissions:
        statuses: read
        pull-requests: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@446798f8213ac2e75931c1b0769676d927801858 # v2.10.0
      with:
        egress-policy: audit

    - uses: dotnet/docs-tools/actions/status-checker@5e8bcc78465d45a7544bba56509a1a69922b6a5a # main
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        docs_path: "docs"
        url_base_path: "dotnet"
